### ISSUE TITLE
[BE] (MockupAPI) 미세먼지 Mockup API 설계

### ISSUE THREAD

**Issue by hsik0225** [codesquad-member-2020/dust-6#5]
- [x] 프로젝트 기본 세팅
* Gradle Project
* 의존성 추가
    * Spring Boot DevTools
    *  Lombok
    * Spring Web
    * H2
    * Handlebars
    * Spring Data JDBC

- [x] 미세먼지 API 스켈레톤 코드 작성

**Comment by suhyunsim** [comment]
기본 세팅 및 스켈레톤 코드 작성 완료했습니다. 풀리퀘스트 확인해주세요~
